### PR TITLE
Upgrade to use golang 1.16

### PR DESCRIPTION
**Pull request by Fedosin**
This commit sets the minimal golang version for the project to 1.16.

### CODE REVIEW

**Comment by nirarg** [comment]
Kubevirt platform support is removed from machine-api-operator
Please see: https://github.com/openshift/machine-api-operator/pull/936 and https://github.com/openshift/machine-api-operator/pull/940
This PR can be closed

**Comment by Fedosin** [comment]
Kubevirt platform support is removed from machine-api-operator
Please see: openshift/machine-api-operator#936 and openshift/machine-api-operator#940

**Pull request closed without merging**
