### PR TITLE
Ensure MAO dependency is up to date to include newest metrics

### PR DESCRIPTION
**Pull request by JoelSpeed**
This updates MAO to the latest version. This should be done periodically to include new updates to the Machine controller code. In particular, this brings in some new metrics that should allow us to debug slow booting machines in the future.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
This doesn't actually do anything for this provider presently, but was automatically created by the script. Do you think you'll be able to up date to a newer MAO at any point in the near future or are you still stuck on the older versions?

**Comment by rgolangh** [comment]
@JoelSpeed where is the vendor update? you didn't run make vendor on purpose?

**Comment by JoelSpeed** [comment]
> @JoelSpeed where is the vendor update? you didn't run make vendor on purpose?

@rgolangh This update was created by a script that didn't take into account the fact you have a replace statement at the moment. I've just pushed an update that includes removing the replacement, not sure if this will work or not. May have to spend a bit of time ironing out some changes

**Comment by JoelSpeed** [comment]
I spent a little time trying to update the dependencies here, but it seems because the kubevirt/client-go package still depends on K8s 1.16, we are stuck on the older versions of MAO until further notice. Is there any likelihood of being able to get the kubevirt/client-go package updated?

**Comment by JoelSpeed** [comment]
I've detached this from the bug for now as I need to get all of the other providers verified for the 4.7 release, we can keep this open or close as you prefer based on my previous comment

**Comment by chenyosef** [comment]
@JoelSpeed I believe this was handled here https://github.com/openshift/cluster-api-provider-kubevirt/pull/23 ?

**Comment by JoelSpeed** [comment]
Yep, thanks for handling that!

**Pull request closed without merging**
